-- ===========================================================================
-- IGM UPDATE AND DO ISSUE — docs/DESIGN-UPDATE-2026-10-04.md §4
-- ===========================================================================
--
-- Two new tables and one enum, both for inbound bookings only:
--
--   igm_update       the HBL No and the uploaded IGM file (sheet `IGM Update`)
--   delivery_order   the DO letter: date, addressee, subject, body, and the
--                    printed copy (sheet `DO issue`)
--
-- Nothing existing is altered. The DDL was generated by `prisma migrate diff`;
-- the integrity, tenancy and audit statements below it are hand-written.
-- ===========================================================================

-- CreateEnum
CREATE TYPE "delivery_order_status" AS ENUM ('ISSUED', 'CANCELLED');

-- CreateTable
CREATE TABLE "igm_update" (
    "tenant_id" BIGINT NOT NULL,
    "id" BIGSERIAL NOT NULL,
    "shipment_id" BIGINT NOT NULL,
    "hbl_no" VARCHAR(64),
    "igm_file" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "igm_update_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "delivery_order" (
    "tenant_id" BIGINT NOT NULL,
    "id" BIGSERIAL NOT NULL,
    "code" VARCHAR(32) NOT NULL,
    "series_year" INTEGER NOT NULL,
    "shipment_id" BIGINT NOT NULL,
    "issue_date" DATE NOT NULL,
    "addressee" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "body" TEXT,
    "status" "delivery_order_status" NOT NULL DEFAULT 'ISSUED',
    "pdf_file" TEXT,
    "issued_by" BIGINT,
    "issued_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "cancelled_by" BIGINT,
    "cancelled_at" TIMESTAMPTZ(6),
    "cancel_reason" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "delivery_order_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "igm_update_tenant_id_idx" ON "igm_update"("tenant_id");

-- CreateIndex
CREATE INDEX "igm_update_shipment_id_idx" ON "igm_update"("shipment_id");

-- CreateIndex
CREATE UNIQUE INDEX "igm_update_tenant_id_id_key" ON "igm_update"("tenant_id", "id");

-- CreateIndex
CREATE INDEX "delivery_order_tenant_id_idx" ON "delivery_order"("tenant_id");

-- CreateIndex
CREATE INDEX "delivery_order_tenant_id_status_idx" ON "delivery_order"("tenant_id", "status");

-- CreateIndex
CREATE INDEX "delivery_order_shipment_id_idx" ON "delivery_order"("shipment_id");

-- CreateIndex
CREATE INDEX "delivery_order_issued_by_idx" ON "delivery_order"("issued_by");

-- CreateIndex
CREATE INDEX "delivery_order_cancelled_by_idx" ON "delivery_order"("cancelled_by");

-- CreateIndex
CREATE UNIQUE INDEX "delivery_order_tenant_id_code_key" ON "delivery_order"("tenant_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "delivery_order_tenant_id_id_key" ON "delivery_order"("tenant_id", "id");

-- AddForeignKey
ALTER TABLE "igm_update" ADD CONSTRAINT "igm_update_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "igm_update" ADD CONSTRAINT "igm_update_shipment_id_fkey" FOREIGN KEY ("tenant_id", "shipment_id") REFERENCES "shipment"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "igm_update" ADD CONSTRAINT "igm_update_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "igm_update" ADD CONSTRAINT "igm_update_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_order" ADD CONSTRAINT "delivery_order_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_order" ADD CONSTRAINT "delivery_order_shipment_id_fkey" FOREIGN KEY ("tenant_id", "shipment_id") REFERENCES "shipment"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_order" ADD CONSTRAINT "delivery_order_issued_by_fkey" FOREIGN KEY ("issued_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_order" ADD CONSTRAINT "delivery_order_cancelled_by_fkey" FOREIGN KEY ("cancelled_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_order" ADD CONSTRAINT "delivery_order_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "delivery_order" ADD CONSTRAINT "delivery_order_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ---------------------------------------------------------------- integrity
-- One live IGM row per booking; saving again updates it.
CREATE UNIQUE INDEX "igm_update_one_live_key"
  ON "igm_update"("tenant_id", "shipment_id")
  WHERE "deleted_at" IS NULL;

-- A saved row says something: the number, the file, or both.
ALTER TABLE "igm_update" ADD CONSTRAINT "igm_update_not_empty"
  CHECK ("hbl_no" IS NOT NULL OR "igm_file" IS NOT NULL);

-- One issued delivery order per booking. A cancelled one stays, numbered.
CREATE UNIQUE INDEX "delivery_order_one_issued_key"
  ON "delivery_order"("tenant_id", "shipment_id")
  WHERE "deleted_at" IS NULL AND "status" = 'ISSUED';

-- Cancelling says why, and when, and who.
ALTER TABLE "delivery_order" ADD CONSTRAINT "delivery_order_cancellation_ck"
  CHECK (
    "status" <> 'CANCELLED'
    OR ("cancelled_at" IS NOT NULL
        AND "cancelled_by" IS NOT NULL
        AND "cancel_reason" IS NOT NULL
        AND length(btrim("cancel_reason")) > 0)
  );

ALTER TABLE "delivery_order" ADD CONSTRAINT "delivery_order_text_not_blank"
  CHECK (length(btrim("addressee")) > 0 AND length(btrim("subject")) > 0);

-- ------------------------------------------------------------------ tenancy
-- The single-comparison form (20260917090000). app_staff_tenant() is NULL for
-- any non-staff session, so an agent or a customer reads nothing here.
ALTER TABLE "igm_update" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "igm_update"
  USING (tenant_id = app_staff_tenant())
  WITH CHECK (tenant_id = app_staff_tenant());

ALTER TABLE "delivery_order" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "delivery_order"
  USING (tenant_id = app_staff_tenant())
  WITH CHECK (tenant_id = app_staff_tenant());

GRANT SELECT, INSERT, UPDATE ON TABLE "igm_update" TO ff_app;
GRANT USAGE, SELECT ON SEQUENCE "igm_update_id_seq" TO ff_app;
GRANT SELECT, INSERT, UPDATE ON TABLE "delivery_order" TO ff_app;
GRANT USAGE, SELECT ON SEQUENCE "delivery_order_id_seq" TO ff_app;

-- §4 rule 7: the audit trail is a trigger, so a write from any path is caught.
CREATE TRIGGER "igm_update_audit"
  AFTER INSERT OR UPDATE OR DELETE ON "igm_update"
  FOR EACH ROW EXECUTE FUNCTION app_audit_row();
CREATE TRIGGER "delivery_order_audit"
  AFTER INSERT OR UPDATE OR DELETE ON "delivery_order"
  FOR EACH ROW EXECUTE FUNCTION app_audit_row();
