-- ===========================================================================
-- TARIFF — docs/DESIGN-UPDATE-2026-10-04.md §5
-- ===========================================================================
--
-- Two new tables and one enum: a price book of local charges at a POL
-- (sheet `Tarrif`, Purchase → Price List).
--
--   tariff        Country · POL · Movement Type · Tariff Type
--   tariff_line   Cost Head · Container Size · Unit · Unit Price · Currency
--
-- tariff_type is an enum of the two values the sheet names (H5). Nothing
-- existing is altered. The DDL was generated by `prisma migrate diff`; the
-- integrity, tenancy, guard and audit statements below it are hand-written.
-- ===========================================================================

-- CreateEnum
CREATE TYPE "tariff_type" AS ENUM ('PORT_TARIFF', 'CFS_CHARGE');

-- CreateTable
CREATE TABLE "tariff" (
    "tenant_id" BIGINT NOT NULL,
    "id" BIGSERIAL NOT NULL,
    "code" VARCHAR(32) NOT NULL,
    "country" VARCHAR(100) NOT NULL,
    "pol_id" BIGINT NOT NULL,
    "movement_type" "movement_type" NOT NULL,
    "tariff_type" "tariff_type" NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "tariff_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tariff_line" (
    "tenant_id" BIGINT NOT NULL,
    "id" BIGSERIAL NOT NULL,
    "tariff_id" BIGINT NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "cost_head_id" BIGINT NOT NULL,
    "container_size_id" BIGINT,
    "cost_unit_id" BIGINT NOT NULL,
    "unit_price" DECIMAL(18,4) NOT NULL,
    "currency_id" BIGINT NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "tariff_line_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "tariff_tenant_id_idx" ON "tariff"("tenant_id");

-- CreateIndex
CREATE INDEX "tariff_pol_id_idx" ON "tariff"("pol_id");

-- CreateIndex
CREATE UNIQUE INDEX "tariff_tenant_id_code_key" ON "tariff"("tenant_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "tariff_tenant_id_id_key" ON "tariff"("tenant_id", "id");

-- CreateIndex
CREATE INDEX "tariff_line_tenant_id_idx" ON "tariff_line"("tenant_id");

-- CreateIndex
CREATE INDEX "tariff_line_tariff_id_idx" ON "tariff_line"("tariff_id");

-- CreateIndex
CREATE INDEX "tariff_line_cost_head_id_idx" ON "tariff_line"("cost_head_id");

-- CreateIndex
CREATE INDEX "tariff_line_container_size_id_idx" ON "tariff_line"("container_size_id");

-- CreateIndex
CREATE INDEX "tariff_line_cost_unit_id_idx" ON "tariff_line"("cost_unit_id");

-- CreateIndex
CREATE INDEX "tariff_line_currency_id_idx" ON "tariff_line"("currency_id");

-- CreateIndex
CREATE UNIQUE INDEX "tariff_line_tenant_id_id_key" ON "tariff_line"("tenant_id", "id");

-- AddForeignKey
ALTER TABLE "tariff" ADD CONSTRAINT "tariff_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tariff" ADD CONSTRAINT "tariff_pol_id_fkey" FOREIGN KEY ("pol_id") REFERENCES "port"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tariff" ADD CONSTRAINT "tariff_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tariff" ADD CONSTRAINT "tariff_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tariff_line" ADD CONSTRAINT "tariff_line_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tariff_line" ADD CONSTRAINT "tariff_line_tariff_id_fkey" FOREIGN KEY ("tenant_id", "tariff_id") REFERENCES "tariff"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tariff_line" ADD CONSTRAINT "tariff_line_cost_head_id_fkey" FOREIGN KEY ("tenant_id", "cost_head_id") REFERENCES "cost_head"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tariff_line" ADD CONSTRAINT "tariff_line_container_size_id_fkey" FOREIGN KEY ("container_size_id") REFERENCES "container_size"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tariff_line" ADD CONSTRAINT "tariff_line_cost_unit_id_fkey" FOREIGN KEY ("cost_unit_id") REFERENCES "cost_unit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tariff_line" ADD CONSTRAINT "tariff_line_currency_id_fkey" FOREIGN KEY ("currency_id") REFERENCES "currency"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tariff_line" ADD CONSTRAINT "tariff_line_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tariff_line" ADD CONSTRAINT "tariff_line_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ---------------------------------------------------------------- integrity
ALTER TABLE "tariff_line" ADD CONSTRAINT "tariff_line_price_not_negative"
  CHECK ("unit_price" >= 0);

-- ------------------------------------------------------------------ tenancy
ALTER TABLE "tariff" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "tariff"
  USING (tenant_id = app_staff_tenant())
  WITH CHECK (tenant_id = app_staff_tenant());

ALTER TABLE "tariff_line" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "tariff_line"
  USING (tenant_id = app_staff_tenant())
  WITH CHECK (tenant_id = app_staff_tenant());

GRANT SELECT, INSERT, UPDATE ON TABLE "tariff" TO ff_app;
GRANT USAGE, SELECT ON SEQUENCE "tariff_id_seq" TO ff_app;
GRANT SELECT, INSERT, UPDATE ON TABLE "tariff_line" TO ff_app;
GRANT USAGE, SELECT ON SEQUENCE "tariff_line_id_seq" TO ff_app;

CREATE TRIGGER "tariff_audit"
  AFTER INSERT OR UPDATE OR DELETE ON "tariff"
  FOR EACH ROW EXECUTE FUNCTION app_audit_row();
CREATE TRIGGER "tariff_line_audit"
  AFTER INSERT OR UPDATE OR DELETE ON "tariff_line"
  FOR EACH ROW EXECUTE FUNCTION app_audit_row();

-- §4 rule 10. Port, container size, unit and currency are system-capable and
-- reached by a single-column key, so the constraint alone cannot say whose row
-- it is; the guard refuses another workspace's private one.
CREATE TRIGGER tariff_pol_id_tenant_guard
  BEFORE INSERT OR UPDATE OF pol_id ON tariff
  FOR EACH ROW EXECUTE FUNCTION app_assert_parent_tenant('port', 'pol_id');
CREATE TRIGGER tariff_line_container_size_id_tenant_guard
  BEFORE INSERT OR UPDATE OF container_size_id ON tariff_line
  FOR EACH ROW EXECUTE FUNCTION app_assert_parent_tenant('container_size', 'container_size_id');
CREATE TRIGGER tariff_line_cost_unit_id_tenant_guard
  BEFORE INSERT OR UPDATE OF cost_unit_id ON tariff_line
  FOR EACH ROW EXECUTE FUNCTION app_assert_parent_tenant('cost_unit', 'cost_unit_id');
CREATE TRIGGER tariff_line_currency_id_tenant_guard
  BEFORE INSERT OR UPDATE OF currency_id ON tariff_line
  FOR EACH ROW EXECUTE FUNCTION app_assert_parent_tenant('currency', 'currency_id');
