-- ===========================================================================
-- DOCUMENTATION MODULE — Shipment Advise and BL Draft
-- docs/MODULE_DOCUMENTATION.md §4
-- ===========================================================================
--
-- Five new tables, three new enums, and two new shipment statuses.
--
--   shipment_advise        one per booking (§3.1) — the document, and where the
--                          House BL number is allocated (§3.3)
--   shipment_advise_line   the PO grid, snapshotted from the CLP (§3.2)
--   bl_draft               the bill of lading, staff and customer alike (§3.6)
--   bl_draft_container     the Marks and Numbers block, pulled from the CLPs
--   bl_template            Make Templet / Use Templet (§3.5)
--
-- shipment_status gains ADVISED and BL_DRAFTED (§3.8). Both worklists are
-- bookings narrowed by status, like every other worklist in the product, and
-- the machine stopped at CARGO_RECEIVED — finalising a CLP moves nothing.
--
-- The DDL below was generated by `prisma migrate diff` and then reduced to the
-- statements belonging to this change. The generator also emits a backlog of
-- pre-existing drift — 48 RenameForeignKey, 12 DropIndex, 11 RenameIndex and
-- 10 updated_at default changes against tables this module does not touch —
-- which is deliberately NOT included here. Sweeping it up in a feature
-- migration would hide a schema change nobody reviewed inside one they did.
-- ===========================================================================

-- CreateEnum
CREATE TYPE "advise_status" AS ENUM ('DRAFT', 'SENT', 'CANCELLED');

-- CreateEnum
CREATE TYPE "bl_draft_status" AS ENUM ('DRAFT', 'SUBMITTED', 'APPROVED', 'SENT', 'CANCELLED');

-- CreateEnum
CREATE TYPE "bl_draft_origin" AS ENUM ('STAFF', 'CUSTOMER');

-- the enum.


ALTER TYPE "shipment_status" ADD VALUE 'ADVISED';
ALTER TYPE "shipment_status" ADD VALUE 'BL_DRAFTED';

-- CreateTable
CREATE TABLE "shipment_advise" (
    "tenant_id" BIGINT NOT NULL,
    "id" BIGSERIAL NOT NULL,
    "code" VARCHAR(32) NOT NULL,
    "series_year" INTEGER NOT NULL,
    "shipment_id" BIGINT NOT NULL,
    "schedule_id" BIGINT,
    "carrier_id" BIGINT NOT NULL,
    "transit_type" "transit_type" NOT NULL,
    "first_vessel_id" BIGINT,
    "voyage_no" TEXT,
    "first_flight_no" TEXT,
    "pol_id" BIGINT NOT NULL,
    "pod_id" BIGINT NOT NULL,
    "etd" TIMESTAMPTZ(6),
    "eta" TIMESTAMPTZ(6),
    "stuffing_date" DATE,
    "house_bl_no" VARCHAR(64) NOT NULL,
    "mbl_no" VARCHAR(64),
    "status" "advise_status" NOT NULL DEFAULT 'DRAFT',
    "sent_at" TIMESTAMPTZ(6),
    "sent_by" BIGINT,
    "email_log_id" BIGINT,
    "cancelled_at" TIMESTAMPTZ(6),
    "cancelled_by" BIGINT,
    "cancel_reason" TEXT,
    "pdf_file" TEXT,
    "total_po_count" INTEGER NOT NULL DEFAULT 0,
    "total_ctn_qty" INTEGER NOT NULL DEFAULT 0,
    "total_pcs_qty" INTEGER,
    "total_net_weight_kg" DECIMAL(18,3),
    "total_gross_weight_kg" DECIMAL(18,3),
    "total_volume_cbm" DECIMAL(18,4),
    "total_chargeable_wt_kg" DECIMAL(18,3),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "shipment_advise_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "shipment_advise_line" (
    "tenant_id" BIGINT NOT NULL,
    "id" BIGSERIAL NOT NULL,
    "advise_id" BIGINT NOT NULL,
    "shipment_po_id" BIGINT NOT NULL,
    "shipment_cargo_line_id" BIGINT NOT NULL,
    "clp_id" BIGINT,
    "po_no" TEXT NOT NULL,
    "item_code" TEXT NOT NULL,
    "sku" TEXT,
    "ctn_qty" INTEGER NOT NULL,
    "pcs_qty" INTEGER,
    "net_weight_kg" DECIMAL(18,3),
    "gross_weight_kg" DECIMAL(18,3),
    "carton_length_cm" DECIMAL(10,3),
    "carton_width_cm" DECIMAL(10,3),
    "carton_height_cm" DECIMAL(10,3),
    "volume_cbm" DECIMAL(18,4),
    "chargeable_wt_kg" DECIMAL(18,3),
    "cargo_receipt_date" DATE,
    "stuffing_date" DATE,
    "efr_no" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "shipment_advise_line_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bl_draft" (
    "tenant_id" BIGINT NOT NULL,
    "id" BIGSERIAL NOT NULL,
    "code" VARCHAR(32) NOT NULL,
    "series_year" INTEGER NOT NULL,
    "shipment_id" BIGINT NOT NULL,
    "advise_id" BIGINT NOT NULL,
    "origin" "bl_draft_origin" NOT NULL DEFAULT 'STAFF',
    "bl_no" VARCHAR(64) NOT NULL,
    "manifest_no" VARCHAR(64),
    "shipper_text" TEXT NOT NULL,
    "consignee_text" TEXT NOT NULL,
    "notify_text" TEXT NOT NULL,
    "also_notify_text" TEXT,
    "export_references" TEXT,
    "forwarding_agent_references" TEXT,
    "point_country_of_origin" TEXT,
    "pre_carriage_by_mode_id" BIGINT NOT NULL,
    "place_of_receipt" TEXT NOT NULL,
    "delivery_agent_id" BIGINT,
    "delivery_agent_text" TEXT,
    "ocean_vessel_voyage" TEXT,
    "pol_id" BIGINT NOT NULL,
    "pod_id" BIGINT NOT NULL,
    "place_of_delivery" TEXT,
    "packages_description" TEXT,
    "marks_and_numbers" TEXT,
    "gross_weight_kg" DECIMAL(18,3),
    "measurement_cbm" DECIMAL(18,4),
    "freight_payable_at" TEXT,
    "original_bl_count" INTEGER,
    "laden_on_board_date" DATE,
    "status" "bl_draft_status" NOT NULL DEFAULT 'DRAFT',
    "submitted_at" TIMESTAMPTZ(6),
    "submitted_by" BIGINT,
    "approved_at" TIMESTAMPTZ(6),
    "approved_by" BIGINT,
    "sent_at" TIMESTAMPTZ(6),
    "sent_by" BIGINT,
    "email_log_id" BIGINT,
    "cancelled_at" TIMESTAMPTZ(6),
    "cancelled_by" BIGINT,
    "cancel_reason" TEXT,
    "pdf_file" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "bl_draft_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bl_draft_container" (
    "tenant_id" BIGINT NOT NULL,
    "id" BIGSERIAL NOT NULL,
    "bl_draft_id" BIGINT NOT NULL,
    "clp_id" BIGINT,
    "container_no" TEXT,
    "container_size" TEXT,
    "seal_no" TEXT,
    "ctn_qty" INTEGER,
    "gross_weight_kg" DECIMAL(18,3),
    "measurement_cbm" DECIMAL(18,4),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "bl_draft_container_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bl_template" (
    "tenant_id" BIGINT NOT NULL,
    "id" BIGSERIAL NOT NULL,
    "code" VARCHAR(32) NOT NULL,
    "customer_id" BIGINT,
    "name" VARCHAR(200) NOT NULL,
    "shipper_text" TEXT,
    "consignee_text" TEXT,
    "notify_text" TEXT,
    "also_notify_text" TEXT,
    "freight_payable_at" TEXT,
    "original_bl_count" INTEGER,
    "delivery_agent_id" BIGINT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "bl_template_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "shipment_advise_tenant_id_idx" ON "shipment_advise"("tenant_id");

-- CreateIndex
CREATE INDEX "shipment_advise_tenant_id_shipment_id_idx" ON "shipment_advise"("tenant_id", "shipment_id");

-- CreateIndex
CREATE INDEX "shipment_advise_tenant_id_status_idx" ON "shipment_advise"("tenant_id", "status");

-- CreateIndex
CREATE INDEX "shipment_advise_schedule_id_idx" ON "shipment_advise"("schedule_id");

-- CreateIndex
CREATE INDEX "shipment_advise_carrier_id_idx" ON "shipment_advise"("carrier_id");

-- CreateIndex
CREATE INDEX "shipment_advise_first_vessel_id_idx" ON "shipment_advise"("first_vessel_id");

-- CreateIndex
CREATE INDEX "shipment_advise_pol_id_idx" ON "shipment_advise"("pol_id");

-- CreateIndex
CREATE INDEX "shipment_advise_pod_id_idx" ON "shipment_advise"("pod_id");

-- CreateIndex
CREATE INDEX "shipment_advise_sent_by_idx" ON "shipment_advise"("sent_by");

-- CreateIndex
CREATE INDEX "shipment_advise_cancelled_by_idx" ON "shipment_advise"("cancelled_by");

-- CreateIndex
CREATE UNIQUE INDEX "shipment_advise_tenant_id_code_key" ON "shipment_advise"("tenant_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "shipment_advise_tenant_id_id_key" ON "shipment_advise"("tenant_id", "id");

-- CreateIndex
CREATE UNIQUE INDEX "shipment_advise_tenant_id_house_bl_no_key" ON "shipment_advise"("tenant_id", "house_bl_no");

-- CreateIndex
CREATE INDEX "shipment_advise_line_tenant_id_idx" ON "shipment_advise_line"("tenant_id");

-- CreateIndex
CREATE INDEX "shipment_advise_line_advise_id_idx" ON "shipment_advise_line"("advise_id");

-- CreateIndex
CREATE INDEX "shipment_advise_line_shipment_po_id_idx" ON "shipment_advise_line"("shipment_po_id");

-- CreateIndex
CREATE INDEX "shipment_advise_line_shipment_cargo_line_id_idx" ON "shipment_advise_line"("shipment_cargo_line_id");

-- CreateIndex
CREATE INDEX "shipment_advise_line_clp_id_idx" ON "shipment_advise_line"("clp_id");

-- CreateIndex
CREATE UNIQUE INDEX "shipment_advise_line_tenant_id_id_key" ON "shipment_advise_line"("tenant_id", "id");

-- CreateIndex
CREATE INDEX "bl_draft_tenant_id_idx" ON "bl_draft"("tenant_id");

-- CreateIndex
CREATE INDEX "bl_draft_tenant_id_shipment_id_idx" ON "bl_draft"("tenant_id", "shipment_id");

-- CreateIndex
CREATE INDEX "bl_draft_tenant_id_status_idx" ON "bl_draft"("tenant_id", "status");

-- CreateIndex
CREATE INDEX "bl_draft_advise_id_idx" ON "bl_draft"("advise_id");

-- CreateIndex
CREATE INDEX "bl_draft_pre_carriage_by_mode_id_idx" ON "bl_draft"("pre_carriage_by_mode_id");

-- CreateIndex
CREATE INDEX "bl_draft_delivery_agent_id_idx" ON "bl_draft"("delivery_agent_id");

-- CreateIndex
CREATE INDEX "bl_draft_pol_id_idx" ON "bl_draft"("pol_id");

-- CreateIndex
CREATE INDEX "bl_draft_pod_id_idx" ON "bl_draft"("pod_id");

-- CreateIndex
CREATE INDEX "bl_draft_submitted_by_idx" ON "bl_draft"("submitted_by");

-- CreateIndex
CREATE INDEX "bl_draft_approved_by_idx" ON "bl_draft"("approved_by");

-- CreateIndex
CREATE INDEX "bl_draft_sent_by_idx" ON "bl_draft"("sent_by");

-- CreateIndex
CREATE UNIQUE INDEX "bl_draft_tenant_id_code_key" ON "bl_draft"("tenant_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "bl_draft_tenant_id_id_key" ON "bl_draft"("tenant_id", "id");

-- CreateIndex
CREATE INDEX "bl_draft_container_tenant_id_idx" ON "bl_draft_container"("tenant_id");

-- CreateIndex
CREATE INDEX "bl_draft_container_bl_draft_id_idx" ON "bl_draft_container"("bl_draft_id");

-- CreateIndex
CREATE INDEX "bl_draft_container_clp_id_idx" ON "bl_draft_container"("clp_id");

-- CreateIndex
CREATE UNIQUE INDEX "bl_draft_container_tenant_id_id_key" ON "bl_draft_container"("tenant_id", "id");

-- CreateIndex
CREATE INDEX "bl_template_tenant_id_idx" ON "bl_template"("tenant_id");

-- CreateIndex
CREATE INDEX "bl_template_customer_id_idx" ON "bl_template"("customer_id");

-- CreateIndex
CREATE INDEX "bl_template_delivery_agent_id_idx" ON "bl_template"("delivery_agent_id");

-- CreateIndex
CREATE UNIQUE INDEX "bl_template_tenant_id_code_key" ON "bl_template"("tenant_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "bl_template_tenant_id_id_key" ON "bl_template"("tenant_id", "id");

-- AddForeignKey
ALTER TABLE "shipment_advise" ADD CONSTRAINT "shipment_advise_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise" ADD CONSTRAINT "shipment_advise_tenant_id_shipment_id_fkey" FOREIGN KEY ("tenant_id", "shipment_id") REFERENCES "shipment"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise" ADD CONSTRAINT "shipment_advise_tenant_id_schedule_id_fkey" FOREIGN KEY ("tenant_id", "schedule_id") REFERENCES "shipment_schedule"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise" ADD CONSTRAINT "shipment_advise_carrier_id_fkey" FOREIGN KEY ("carrier_id") REFERENCES "carrier"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise" ADD CONSTRAINT "shipment_advise_first_vessel_id_fkey" FOREIGN KEY ("first_vessel_id") REFERENCES "vessel"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise" ADD CONSTRAINT "shipment_advise_pol_id_fkey" FOREIGN KEY ("pol_id") REFERENCES "port"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise" ADD CONSTRAINT "shipment_advise_pod_id_fkey" FOREIGN KEY ("pod_id") REFERENCES "port"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise" ADD CONSTRAINT "shipment_advise_sent_by_fkey" FOREIGN KEY ("sent_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise" ADD CONSTRAINT "shipment_advise_cancelled_by_fkey" FOREIGN KEY ("cancelled_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise" ADD CONSTRAINT "shipment_advise_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise" ADD CONSTRAINT "shipment_advise_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise_line" ADD CONSTRAINT "shipment_advise_line_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise_line" ADD CONSTRAINT "shipment_advise_line_tenant_id_advise_id_fkey" FOREIGN KEY ("tenant_id", "advise_id") REFERENCES "shipment_advise"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise_line" ADD CONSTRAINT "shipment_advise_line_tenant_id_shipment_po_id_fkey" FOREIGN KEY ("tenant_id", "shipment_po_id") REFERENCES "shipment_po"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise_line" ADD CONSTRAINT "shipment_advise_line_tenant_id_shipment_cargo_line_id_fkey" FOREIGN KEY ("tenant_id", "shipment_cargo_line_id") REFERENCES "shipment_cargo_line"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise_line" ADD CONSTRAINT "shipment_advise_line_tenant_id_clp_id_fkey" FOREIGN KEY ("tenant_id", "clp_id") REFERENCES "clp"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise_line" ADD CONSTRAINT "shipment_advise_line_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_advise_line" ADD CONSTRAINT "shipment_advise_line_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft" ADD CONSTRAINT "bl_draft_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft" ADD CONSTRAINT "bl_draft_tenant_id_shipment_id_fkey" FOREIGN KEY ("tenant_id", "shipment_id") REFERENCES "shipment"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft" ADD CONSTRAINT "bl_draft_tenant_id_advise_id_fkey" FOREIGN KEY ("tenant_id", "advise_id") REFERENCES "shipment_advise"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft" ADD CONSTRAINT "bl_draft_pre_carriage_by_mode_id_fkey" FOREIGN KEY ("pre_carriage_by_mode_id") REFERENCES "mode"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft" ADD CONSTRAINT "bl_draft_tenant_id_delivery_agent_id_fkey" FOREIGN KEY ("tenant_id", "delivery_agent_id") REFERENCES "agent"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft" ADD CONSTRAINT "bl_draft_pol_id_fkey" FOREIGN KEY ("pol_id") REFERENCES "port"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft" ADD CONSTRAINT "bl_draft_pod_id_fkey" FOREIGN KEY ("pod_id") REFERENCES "port"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft" ADD CONSTRAINT "bl_draft_submitted_by_fkey" FOREIGN KEY ("submitted_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft" ADD CONSTRAINT "bl_draft_approved_by_fkey" FOREIGN KEY ("approved_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft" ADD CONSTRAINT "bl_draft_sent_by_fkey" FOREIGN KEY ("sent_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft" ADD CONSTRAINT "bl_draft_cancelled_by_fkey" FOREIGN KEY ("cancelled_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft" ADD CONSTRAINT "bl_draft_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft" ADD CONSTRAINT "bl_draft_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft_container" ADD CONSTRAINT "bl_draft_container_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft_container" ADD CONSTRAINT "bl_draft_container_tenant_id_bl_draft_id_fkey" FOREIGN KEY ("tenant_id", "bl_draft_id") REFERENCES "bl_draft"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft_container" ADD CONSTRAINT "bl_draft_container_tenant_id_clp_id_fkey" FOREIGN KEY ("tenant_id", "clp_id") REFERENCES "clp"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft_container" ADD CONSTRAINT "bl_draft_container_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_draft_container" ADD CONSTRAINT "bl_draft_container_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_template" ADD CONSTRAINT "bl_template_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_template" ADD CONSTRAINT "bl_template_tenant_id_customer_id_fkey" FOREIGN KEY ("tenant_id", "customer_id") REFERENCES "customer"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_template" ADD CONSTRAINT "bl_template_tenant_id_delivery_agent_id_fkey" FOREIGN KEY ("tenant_id", "delivery_agent_id") REFERENCES "agent"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_template" ADD CONSTRAINT "bl_template_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bl_template" ADD CONSTRAINT "bl_template_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ---------------------------------------------------------- natural keys
-- One live advise per booking (§3.1). Partial, so a cancelled-and-soft-deleted
-- advise does not reserve the booking forever — the same reason port_code's
-- unique index is partial (CR-002).
CREATE UNIQUE INDEX "shipment_advise_tenant_id_shipment_id_live_key"
  ON "shipment_advise" ("tenant_id", "shipment_id")
  WHERE "deleted_at" IS NULL AND "status" <> 'CANCELLED';

-- One live BL draft per booking. §3.6 makes the customer's copy and the staff
-- copy the same document in different states, so two live rows for one booking
-- would be exactly the split that decision refuses.
CREATE UNIQUE INDEX "bl_draft_tenant_id_shipment_id_live_key"
  ON "bl_draft" ("tenant_id", "shipment_id")
  WHERE "deleted_at" IS NULL AND "status" <> 'CANCELLED';

-- ------------------------------------------------------------------ tenancy
-- The single-comparison form (20260917090000). app_staff_tenant() is NULL for
-- any non-staff session, so these deny an agent and a customer alike; the
-- customer openings are added by the customer access migration, one table at
-- a time.
ALTER TABLE "shipment_advise" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "shipment_advise"
  USING (tenant_id = app_staff_tenant())
  WITH CHECK (tenant_id = app_staff_tenant());

ALTER TABLE "shipment_advise_line" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "shipment_advise_line"
  USING (tenant_id = app_staff_tenant())
  WITH CHECK (tenant_id = app_staff_tenant());

ALTER TABLE "bl_draft" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "bl_draft"
  USING (tenant_id = app_staff_tenant())
  WITH CHECK (tenant_id = app_staff_tenant());

ALTER TABLE "bl_draft_container" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "bl_draft_container"
  USING (tenant_id = app_staff_tenant())
  WITH CHECK (tenant_id = app_staff_tenant());

ALTER TABLE "bl_template" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "bl_template"
  USING (tenant_id = app_staff_tenant())
  WITH CHECK (tenant_id = app_staff_tenant());

GRANT SELECT, INSERT, UPDATE ON TABLE "shipment_advise" TO ff_app;
GRANT USAGE, SELECT ON SEQUENCE "shipment_advise_id_seq" TO ff_app;
GRANT SELECT, INSERT, UPDATE ON TABLE "shipment_advise_line" TO ff_app;
GRANT USAGE, SELECT ON SEQUENCE "shipment_advise_line_id_seq" TO ff_app;
GRANT SELECT, INSERT, UPDATE ON TABLE "bl_draft" TO ff_app;
GRANT USAGE, SELECT ON SEQUENCE "bl_draft_id_seq" TO ff_app;
GRANT SELECT, INSERT, UPDATE ON TABLE "bl_draft_container" TO ff_app;
GRANT USAGE, SELECT ON SEQUENCE "bl_draft_container_id_seq" TO ff_app;
GRANT SELECT, INSERT, UPDATE ON TABLE "bl_template" TO ff_app;
GRANT USAGE, SELECT ON SEQUENCE "bl_template_id_seq" TO ff_app;

-- §4 rule 7: the audit trail is a trigger, so a write from any path is caught.
CREATE TRIGGER "shipment_advise_audit"
  AFTER INSERT OR UPDATE OR DELETE ON "shipment_advise"
  FOR EACH ROW EXECUTE FUNCTION app_audit_row();
CREATE TRIGGER "shipment_advise_line_audit"
  AFTER INSERT OR UPDATE OR DELETE ON "shipment_advise_line"
  FOR EACH ROW EXECUTE FUNCTION app_audit_row();
CREATE TRIGGER "bl_draft_audit"
  AFTER INSERT OR UPDATE OR DELETE ON "bl_draft"
  FOR EACH ROW EXECUTE FUNCTION app_audit_row();
CREATE TRIGGER "bl_draft_container_audit"
  AFTER INSERT OR UPDATE OR DELETE ON "bl_draft_container"
  FOR EACH ROW EXECUTE FUNCTION app_audit_row();
CREATE TRIGGER "bl_template_audit"
  AFTER INSERT OR UPDATE OR DELETE ON "bl_template"
  FOR EACH ROW EXECUTE FUNCTION app_audit_row();

-- §4 rule 10. carrier, port and mode are system-capable and vessel is reached
-- by a single-column foreign key, so the constraint alone cannot say whose row
-- it is — a plain FK would accept another workspace's private carrier quite
-- happily.
CREATE TRIGGER shipment_advise_carrier_id_tenant_guard
  BEFORE INSERT OR UPDATE OF carrier_id ON shipment_advise
  FOR EACH ROW EXECUTE FUNCTION app_assert_parent_tenant('carrier', 'carrier_id');
CREATE TRIGGER shipment_advise_first_vessel_id_tenant_guard
  BEFORE INSERT OR UPDATE OF first_vessel_id ON shipment_advise
  FOR EACH ROW EXECUTE FUNCTION app_assert_parent_tenant('vessel', 'first_vessel_id');
CREATE TRIGGER shipment_advise_pol_id_tenant_guard
  BEFORE INSERT OR UPDATE OF pol_id ON shipment_advise
  FOR EACH ROW EXECUTE FUNCTION app_assert_parent_tenant('port', 'pol_id');
CREATE TRIGGER shipment_advise_pod_id_tenant_guard
  BEFORE INSERT OR UPDATE OF pod_id ON shipment_advise
  FOR EACH ROW EXECUTE FUNCTION app_assert_parent_tenant('port', 'pod_id');

CREATE TRIGGER bl_draft_pre_carriage_by_mode_id_tenant_guard
  BEFORE INSERT OR UPDATE OF pre_carriage_by_mode_id ON bl_draft
  FOR EACH ROW EXECUTE FUNCTION app_assert_parent_tenant('mode', 'pre_carriage_by_mode_id');
CREATE TRIGGER bl_draft_pol_id_tenant_guard
  BEFORE INSERT OR UPDATE OF pol_id ON bl_draft
  FOR EACH ROW EXECUTE FUNCTION app_assert_parent_tenant('port', 'pol_id');
CREATE TRIGGER bl_draft_pod_id_tenant_guard
  BEFORE INSERT OR UPDATE OF pod_id ON bl_draft
  FOR EACH ROW EXECUTE FUNCTION app_assert_parent_tenant('port', 'pod_id');
