-- ===========================================================================
-- PRE-ALERT — docs/DESIGN-UPDATE-2026-10-04.md §3
-- ===========================================================================
--
-- Two new tables and one enum:
--
--   pre_alert_document   a file uploaded for a booking's pre-alert, one live
--                        per booking per kind (the carrier's papers, which the
--                        system does not make)
--   pre_alert            one sent pre-alert: the agent, the addresses, the
--                        documents ticked, and the letter
--
-- Nothing existing is altered. The DDL was generated by `prisma migrate diff`;
-- the integrity, tenancy and audit statements below it are hand-written.
-- ===========================================================================

-- CreateEnum
CREATE TYPE "pre_alert_document_kind" AS ENUM ('BOOKING_CONFIRMATION', 'HBL', 'MBL', 'HAWB', 'MAWB', 'MANIFEST_AIR', 'DEBIT_NOTE');

-- CreateTable
CREATE TABLE "pre_alert_document" (
    "tenant_id" BIGINT NOT NULL,
    "id" BIGSERIAL NOT NULL,
    "shipment_id" BIGINT NOT NULL,
    "kind" "pre_alert_document_kind" NOT NULL,
    "file_key" TEXT NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "pre_alert_document_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "pre_alert" (
    "tenant_id" BIGINT NOT NULL,
    "id" BIGSERIAL NOT NULL,
    "shipment_id" BIGINT NOT NULL,
    "agent_id" BIGINT NOT NULL,
    "to_addresses" TEXT[],
    "documents" "pre_alert_document_kind"[],
    "email_log_id" BIGINT,
    "sent_by" BIGINT,
    "sent_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "pre_alert_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "pre_alert_document_tenant_id_idx" ON "pre_alert_document"("tenant_id");

-- CreateIndex
CREATE INDEX "pre_alert_document_shipment_id_idx" ON "pre_alert_document"("shipment_id");

-- CreateIndex
CREATE UNIQUE INDEX "pre_alert_document_tenant_id_id_key" ON "pre_alert_document"("tenant_id", "id");

-- CreateIndex
CREATE INDEX "pre_alert_tenant_id_idx" ON "pre_alert"("tenant_id");

-- CreateIndex
CREATE INDEX "pre_alert_shipment_id_idx" ON "pre_alert"("shipment_id");

-- CreateIndex
CREATE INDEX "pre_alert_agent_id_idx" ON "pre_alert"("agent_id");

-- CreateIndex
CREATE INDEX "pre_alert_sent_by_idx" ON "pre_alert"("sent_by");

-- CreateIndex
CREATE UNIQUE INDEX "pre_alert_tenant_id_id_key" ON "pre_alert"("tenant_id", "id");

-- AddForeignKey
ALTER TABLE "pre_alert_document" ADD CONSTRAINT "pre_alert_document_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pre_alert_document" ADD CONSTRAINT "pre_alert_document_shipment_id_fkey" FOREIGN KEY ("tenant_id", "shipment_id") REFERENCES "shipment"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pre_alert_document" ADD CONSTRAINT "pre_alert_document_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pre_alert_document" ADD CONSTRAINT "pre_alert_document_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pre_alert" ADD CONSTRAINT "pre_alert_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pre_alert" ADD CONSTRAINT "pre_alert_shipment_id_fkey" FOREIGN KEY ("tenant_id", "shipment_id") REFERENCES "shipment"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pre_alert" ADD CONSTRAINT "pre_alert_agent_id_fkey" FOREIGN KEY ("tenant_id", "agent_id") REFERENCES "agent"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pre_alert" ADD CONSTRAINT "pre_alert_sent_by_fkey" FOREIGN KEY ("sent_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pre_alert" ADD CONSTRAINT "pre_alert_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pre_alert" ADD CONSTRAINT "pre_alert_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ---------------------------------------------------------------- integrity
CREATE UNIQUE INDEX "pre_alert_document_one_live_key"
  ON "pre_alert_document"("tenant_id", "shipment_id", "kind")
  WHERE "deleted_at" IS NULL;

-- A pre-alert went somewhere and carried something.
ALTER TABLE "pre_alert" ADD CONSTRAINT "pre_alert_not_empty"
  CHECK (cardinality("to_addresses") > 0 AND cardinality("documents") > 0);

-- ------------------------------------------------------------------ tenancy
ALTER TABLE "pre_alert_document" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "pre_alert_document"
  USING (tenant_id = app_staff_tenant())
  WITH CHECK (tenant_id = app_staff_tenant());

ALTER TABLE "pre_alert" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "pre_alert"
  USING (tenant_id = app_staff_tenant())
  WITH CHECK (tenant_id = app_staff_tenant());

GRANT SELECT, INSERT, UPDATE ON TABLE "pre_alert_document" TO ff_app;
GRANT USAGE, SELECT ON SEQUENCE "pre_alert_document_id_seq" TO ff_app;
GRANT SELECT, INSERT, UPDATE ON TABLE "pre_alert" TO ff_app;
GRANT USAGE, SELECT ON SEQUENCE "pre_alert_id_seq" TO ff_app;

CREATE TRIGGER "pre_alert_document_audit"
  AFTER INSERT OR UPDATE OR DELETE ON "pre_alert_document"
  FOR EACH ROW EXECUTE FUNCTION app_audit_row();
CREATE TRIGGER "pre_alert_audit"
  AFTER INSERT OR UPDATE OR DELETE ON "pre_alert"
  FOR EACH ROW EXECUTE FUNCTION app_audit_row();
