import { Prisma } from '../generated/prisma/client';
import { formatCode } from '@ff/shared';

import type { TenantDb } from './tenant-client';

/**
 * Business code generation (CLAUDE.md §4 rule 2): a human-readable id like
 * PL-001, sequenced per tenant per table.
 *
 * §4 says "generated by sequence". A real Postgres sequence per tenant per
 * table would mean thousands of sequence objects and a DDL statement every time
 * a workspace is created, so this reads the current maximum for the tenant
 * inside the caller's transaction and adds one.
 *
 * Two callers racing would compute the same number, which is why the composite
 * UNIQUE(tenant_id, code) is the real guarantee — the loser gets a unique
 * violation and retries. Correctness rests on the constraint, not on this
 * function winning the race.
 */

/**
 * Whitelist of table names. The table name cannot be parameterised in SQL, so
 * it is never taken from caller input — only from this map.
 */
const CODE_TABLES = {
  port: 'port',
  costHead: 'cost_head',
  costUnit: 'cost_unit',
  currency: 'currency',
  carrier: 'carrier',
  carrierType: 'carrier_type',
  carrierPic: 'carrier_pic',
  carrierServicePort: 'carrier_service_port',
  carrierPortPair: 'carrier_port_pair',
  vessel: 'vessel',
  vendor: 'vendor',
  vendorType: 'vendor_type',
  vendorPic: 'vendor_pic',
  industrySector: 'industry_sector',
  commodityItem: 'commodity_item',
  customer: 'customer',
  customerPic: 'customer_pic',
  agent: 'agent',
  agentPic: 'agent_pic',
  agentQuote: 'agent_quote',
  employee: 'employee',
  freightRate: 'freight_rate',
  salesLead: 'sales_lead',
  role: 'role',
  user: 'user',
} as const;

export type CodeTable = keyof typeof CODE_TABLES;

/** Retries a create that lost a code race. */
export const CODE_RETRY_LIMIT = 5;

/**
 * Next code for this tenant in this table.
 *
 * Only the tenant's OWN rows are counted. A system row (tenant_id IS NULL) has
 * its own series, so a workspace adding its first port gets PL-001 even though
 * shared ports already occupy PL-001 upward — the two never collide, because
 * the partial unique index scopes system codes separately.
 */
export async function nextCode(
  db: TenantDb,
  table: CodeTable,
  prefix: string,
  tenantId: bigint,
): Promise<string> {
  const tableName = CODE_TABLES[table];

  const rows = await db.$queryRaw<{ max_seq: number | null }[]>`
    SELECT MAX(
             CASE WHEN code ~ ('^' || ${prefix} || '-[0-9]+$')
                  THEN (regexp_replace(code, '^.*-', ''))::int
             END
           ) AS max_seq
    FROM ${Prisma.raw(`"${tableName}"`)}
    WHERE tenant_id = ${tenantId}
  `;

  const current = rows[0]?.max_seq ?? 0;
  return formatCode(prefix, current + 1);
}

/** True when an error is a unique-constraint violation on the given column. */
export function isUniqueViolation(error: unknown, column?: string): boolean {
  if (
    typeof error !== 'object' ||
    error === null ||
    !('code' in error) ||
    (error as { code: unknown }).code !== 'P2002'
  ) {
    return false;
  }
  if (column === undefined) return true;

  const meta = (error as { meta?: { target?: unknown } }).meta;
  const target = meta?.target;
  if (Array.isArray(target)) return target.includes(column);
  if (typeof target === 'string') return target.includes(column);

  // Prisma 7's driver adapters frequently report the target as "not available",
  // and String(undefined) matched nothing — so every retry guarded by a column
  // name silently stopped retrying and surfaced a 500 instead. The constraint
  // name is still in the message, and it carries the column: a unique index on
  // `code` is named <table>_tenant_id_code_key.
  const message = `${(error as { message?: string }).message ?? ''}`;
  return new RegExp(`_${column}_key|\b${column}\b`).test(message);
}

/**
 * ORDER BY expression that sorts business codes by their number, not as text.
 *
 * `formatCode` pads to CODE_PAD_LENGTH and then grows, so a table past its
 * padding produces PL-999 and PL-1000 — and plain text ordering puts PL-1000
 * before PL-999. The §12 code column is the anchor an operator scans down, so
 * that is a correctness bug, not a cosmetic one.
 *
 * Splitting on the hyphen keeps the prefix as the leading sort key, so this
 * stays right if a table ever holds more than one prefix, and the fixed lpad
 * makes every suffix compare numerically whatever width it was written at —
 * which means it also survives the open question about three digits versus six.
 */
export function codeSortSql(column: string): string {
  return `(split_part(${column}, '-', 1), lpad(split_part(${column}, '-', 2), 12, '0'))`;
}
