-- ===========================================================================
-- LOCAL SALES — ACTIVITY LOG — docs/DESIGN-UPDATE-2026-10-04.md §6
-- ===========================================================================
--
-- One new table: customer_activity, the Local Sales sheet's Activity Log —
-- a meeting or call with a customer, the PIC met, a summary, the next
-- follow-up, the competition, and the possibility of business.
--
-- Nothing existing is altered: the Local Sales list itself is a view over
-- customer (sheet R7: "Table_Customer"). The DDL was generated by
-- `prisma migrate diff`; the integrity, tenancy and audit statements below it
-- are hand-written.
-- ===========================================================================

-- CreateTable
CREATE TABLE "customer_activity" (
    "tenant_id" BIGINT NOT NULL,
    "id" BIGSERIAL NOT NULL,
    "customer_id" BIGINT NOT NULL,
    "activity_at" TIMESTAMPTZ(6) NOT NULL,
    "customer_pic_id" BIGINT,
    "meeting_summary" TEXT NOT NULL,
    "next_followup_date" DATE,
    "competitor_analysis" TEXT,
    "business_possibility" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "customer_activity_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "customer_activity_tenant_id_idx" ON "customer_activity"("tenant_id");

-- CreateIndex
CREATE INDEX "customer_activity_customer_id_idx" ON "customer_activity"("customer_id");

-- CreateIndex
CREATE INDEX "customer_activity_customer_pic_id_idx" ON "customer_activity"("customer_pic_id");

-- CreateIndex
CREATE INDEX "customer_activity_tenant_id_next_followup_date_idx" ON "customer_activity"("tenant_id", "next_followup_date");

-- CreateIndex
CREATE UNIQUE INDEX "customer_activity_tenant_id_id_key" ON "customer_activity"("tenant_id", "id");

-- AddForeignKey
ALTER TABLE "customer_activity" ADD CONSTRAINT "customer_activity_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_activity" ADD CONSTRAINT "customer_activity_customer_id_fkey" FOREIGN KEY ("tenant_id", "customer_id") REFERENCES "customer"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_activity" ADD CONSTRAINT "customer_activity_customer_pic_id_fkey" FOREIGN KEY ("tenant_id", "customer_pic_id") REFERENCES "customer_pic"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_activity" ADD CONSTRAINT "customer_activity_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_activity" ADD CONSTRAINT "customer_activity_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ---------------------------------------------------------------- integrity
ALTER TABLE "customer_activity" ADD CONSTRAINT "customer_activity_summary_not_blank"
  CHECK (length(btrim("meeting_summary")) > 0);

-- The PIC met is one of this customer's own people, not just any customer's.
CREATE FUNCTION app_assert_activity_pic() RETURNS trigger
  LANGUAGE plpgsql
  AS $$
BEGIN
  IF NEW.customer_pic_id IS NOT NULL AND NOT EXISTS (
       SELECT 1 FROM customer_pic p
        WHERE p.tenant_id = NEW.tenant_id
          AND p.id = NEW.customer_pic_id
          AND p.customer_id = NEW.customer_id
     ) THEN
    RAISE EXCEPTION 'customer_pic % is not a contact of customer %', NEW.customer_pic_id, NEW.customer_id
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER customer_activity_pic_guard
  BEFORE INSERT OR UPDATE OF customer_pic_id, customer_id ON customer_activity
  FOR EACH ROW EXECUTE FUNCTION app_assert_activity_pic();

-- ------------------------------------------------------------------ tenancy
ALTER TABLE "customer_activity" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "customer_activity"
  USING (tenant_id = app_staff_tenant())
  WITH CHECK (tenant_id = app_staff_tenant());

GRANT SELECT, INSERT, UPDATE ON TABLE "customer_activity" TO ff_app;
GRANT USAGE, SELECT ON SEQUENCE "customer_activity_id_seq" TO ff_app;

CREATE TRIGGER "customer_activity_audit"
  AFTER INSERT OR UPDATE OR DELETE ON "customer_activity"
  FOR EACH ROW EXECUTE FUNCTION app_audit_row();
