/**
 * Business code prefixes (CLAUDE.md §4 rule 2).
 *
 * Every entity row carries a human-readable `code` like `PL-001`, generated by
 * a sequence **per tenant per table**. The client specified only `PL-001` for
 * port; the rest follow the same shape — three uppercase letters, a hyphen, and
 * a zero-padded counter that grows past three digits naturally (PL-999, PL-1000).
 *
 * `PL` is kept exactly as the client wrote it. Everything else is a three-letter
 * abbreviation of the table name, chosen so no two collide.
 *
 * Tables deliberately WITHOUT a business code, because no user ever refers to
 * one by name — they are reached through their parent or are infrastructure:
 *   - pure join tables: agent_expert_area, agent_port_coverage,
 *     agent_network_member, role_permission, user_permission
 *   - 1:1 extensions reached via the parent: employee_cv, employee_salary
 *   - infrastructure: permission, audit_log, tenant_master_override,
 *     platform_user
 */
export const CODE_PREFIX = {
  // Platform
  tenant: 'TNT',

  // §5 Settings
  port: 'PL', // client-specified: PL-001
  costHead: 'CHD',
  costUnit: 'CUN',
  currency: 'CUR',
  currencyRateHistory: 'CRH',
  carrier: 'CAR',
  carrierType: 'CAT',
  carrierPic: 'CAP',
  carrierServicePort: 'CSP',
  vessel: 'VSL',
  vendor: 'VEN',
  vendorType: 'VET',
  vendorPic: 'VEP',
  industrySector: 'ISC',
  commodityItem: 'CIT',

  goodsType: 'GDT',
  containerType: 'CNT',
  rateTier: 'RTR',
  tos: 'TOS',
  inquirySource: 'INS',

  // §6 CRM
  customer: 'CUS',
  customerPic: 'CUP',
  expertArea: 'EXA',
  network: 'NET',
  agent: 'AGT',
  agentPic: 'AGP',
  employee: 'EMP',

  // Purchase (docs/MODULE_PURCHASE_SALES.md §3.2). The spec writes RATE-000001
  // for freight_rate; the shared padder produces RATE-001 and grows from there,
  // which keeps one code format across the whole product rather than two.
  freightRate: 'RATE',

  // §7 RBAC
  role: 'ROL',
  user: 'USR',
} as const satisfies Record<string, string>;

export type CodePrefixKey = keyof typeof CODE_PREFIX;

/** Minimum digits in the counter. Codes grow past this rather than wrapping. */
export const CODE_PAD_LENGTH = 3;

/** Renders a business code: formatCode('PL', 1) === 'PL-001'. */
export function formatCode(prefix: string, sequence: number): string {
  return `${prefix}-${String(sequence).padStart(CODE_PAD_LENGTH, '0')}`;
}
