-- ===========================================================================
-- DEPART-ARRIVE CONFIRMATION — docs/DESIGN-UPDATE-2026-10-04.md §2
-- ===========================================================================
--
-- One new table and one enum. shipment_milestone holds the three
-- confirmations of the client's `Depart-Arrival Landing page`: On board
-- (DEPARTED), Transshipment (TRANSSHIPPED, indirect routes only) and Arrival
-- (ARRIVED), one live row per booking per kind.
--
-- Nothing existing is altered. bl_draft.laden_on_board_date is written by the
-- API when a departure is confirmed; the column already exists.
--
-- The DDL was generated by `prisma migrate diff` against the database; the
-- tenancy, audit and integrity statements below it are hand-written, as in
-- every feature migration.
-- ===========================================================================

-- CreateEnum
CREATE TYPE "milestone_kind" AS ENUM ('DEPARTED', 'TRANSSHIPPED', 'ARRIVED');

-- CreateTable
CREATE TABLE "shipment_milestone" (
    "tenant_id" BIGINT NOT NULL,
    "id" BIGSERIAL NOT NULL,
    "shipment_id" BIGINT NOT NULL,
    "kind" "milestone_kind" NOT NULL,
    "pulled_on" DATE,
    "confirmed_on" DATE NOT NULL,
    "change_reason" TEXT,
    "confirmed_by" BIGINT,
    "confirmed_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "email_log_id" BIGINT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "shipment_milestone_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "shipment_milestone_tenant_id_idx" ON "shipment_milestone"("tenant_id");

-- CreateIndex
CREATE INDEX "shipment_milestone_tenant_id_kind_idx" ON "shipment_milestone"("tenant_id", "kind");

-- CreateIndex
CREATE INDEX "shipment_milestone_shipment_id_idx" ON "shipment_milestone"("shipment_id");

-- CreateIndex
CREATE INDEX "shipment_milestone_confirmed_by_idx" ON "shipment_milestone"("confirmed_by");

-- CreateIndex
CREATE UNIQUE INDEX "shipment_milestone_tenant_id_id_key" ON "shipment_milestone"("tenant_id", "id");

-- AddForeignKey
ALTER TABLE "shipment_milestone" ADD CONSTRAINT "shipment_milestone_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_milestone" ADD CONSTRAINT "shipment_milestone_shipment_id_fkey" FOREIGN KEY ("tenant_id", "shipment_id") REFERENCES "shipment"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_milestone" ADD CONSTRAINT "shipment_milestone_confirmed_by_fkey" FOREIGN KEY ("confirmed_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_milestone" ADD CONSTRAINT "shipment_milestone_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shipment_milestone" ADD CONSTRAINT "shipment_milestone_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ---------------------------------------------------------------- integrity
-- One live confirmation per booking per kind. A correction updates the row;
-- the partial index leaves room for a retired one to be kept.
CREATE UNIQUE INDEX "shipment_milestone_one_live_key"
  ON "shipment_milestone"("tenant_id", "shipment_id", "kind")
  WHERE "deleted_at" IS NULL;

-- A reason, when given, says something.
ALTER TABLE "shipment_milestone" ADD CONSTRAINT "shipment_milestone_reason_not_blank"
  CHECK ("change_reason" IS NULL OR length(btrim("change_reason")) > 0);

-- ------------------------------------------------------------------ tenancy
-- The single-comparison form (20260917090000). app_staff_tenant() is NULL for
-- any non-staff session, so an agent or a customer reads nothing here.
ALTER TABLE "shipment_milestone" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "shipment_milestone"
  USING (tenant_id = app_staff_tenant())
  WITH CHECK (tenant_id = app_staff_tenant());

GRANT SELECT, INSERT, UPDATE ON TABLE "shipment_milestone" TO ff_app;
GRANT USAGE, SELECT ON SEQUENCE "shipment_milestone_id_seq" TO ff_app;

-- §4 rule 7: the audit trail is a trigger, so a write from any path is caught.
CREATE TRIGGER "shipment_milestone_audit"
  AFTER INSERT OR UPDATE OR DELETE ON "shipment_milestone"
  FOR EACH ROW EXECUTE FUNCTION app_audit_row();
